/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.bytatech.ayoos.appointment.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ConsultationInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5652414462371496479L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ConsultationInfo\",\"namespace\":\"com.bytatech.ayoos.appointment.avro\",\"fields\":[{\"name\":\"height\",\"type\":\"float\"},{\"name\":\"weight\",\"type\":\"float\"},{\"name\":\"age\",\"type\":\"int\"},{\"name\":\"symptoms\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Symptom\",\"fields\":[{\"name\":\"ref\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"numberOfDaysSuffering\",\"type\":\"int\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ConsultationInfo> ENCODER =
      new BinaryMessageEncoder<ConsultationInfo>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ConsultationInfo> DECODER =
      new BinaryMessageDecoder<ConsultationInfo>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ConsultationInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ConsultationInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ConsultationInfo>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ConsultationInfo to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ConsultationInfo from a ByteBuffer. */
  public static ConsultationInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public float height;
  @Deprecated public float weight;
  @Deprecated public int age;
  @Deprecated public java.util.List<com.bytatech.ayoos.appointment.avro.Symptom> symptoms;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ConsultationInfo() {}

  /**
   * All-args constructor.
   * @param height The new value for height
   * @param weight The new value for weight
   * @param age The new value for age
   * @param symptoms The new value for symptoms
   */
  public ConsultationInfo(java.lang.Float height, java.lang.Float weight, java.lang.Integer age, java.util.List<com.bytatech.ayoos.appointment.avro.Symptom> symptoms) {
    this.height = height;
    this.weight = weight;
    this.age = age;
    this.symptoms = symptoms;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return height;
    case 1: return weight;
    case 2: return age;
    case 3: return symptoms;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: height = (java.lang.Float)value$; break;
    case 1: weight = (java.lang.Float)value$; break;
    case 2: age = (java.lang.Integer)value$; break;
    case 3: symptoms = (java.util.List<com.bytatech.ayoos.appointment.avro.Symptom>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'height' field.
   * @return The value of the 'height' field.
   */
  public java.lang.Float getHeight() {
    return height;
  }

  /**
   * Sets the value of the 'height' field.
   * @param value the value to set.
   */
  public void setHeight(java.lang.Float value) {
    this.height = value;
  }

  /**
   * Gets the value of the 'weight' field.
   * @return The value of the 'weight' field.
   */
  public java.lang.Float getWeight() {
    return weight;
  }

  /**
   * Sets the value of the 'weight' field.
   * @param value the value to set.
   */
  public void setWeight(java.lang.Float value) {
    this.weight = value;
  }

  /**
   * Gets the value of the 'age' field.
   * @return The value of the 'age' field.
   */
  public java.lang.Integer getAge() {
    return age;
  }

  /**
   * Sets the value of the 'age' field.
   * @param value the value to set.
   */
  public void setAge(java.lang.Integer value) {
    this.age = value;
  }

  /**
   * Gets the value of the 'symptoms' field.
   * @return The value of the 'symptoms' field.
   */
  public java.util.List<com.bytatech.ayoos.appointment.avro.Symptom> getSymptoms() {
    return symptoms;
  }

  /**
   * Sets the value of the 'symptoms' field.
   * @param value the value to set.
   */
  public void setSymptoms(java.util.List<com.bytatech.ayoos.appointment.avro.Symptom> value) {
    this.symptoms = value;
  }

  /**
   * Creates a new ConsultationInfo RecordBuilder.
   * @return A new ConsultationInfo RecordBuilder
   */
  public static com.bytatech.ayoos.appointment.avro.ConsultationInfo.Builder newBuilder() {
    return new com.bytatech.ayoos.appointment.avro.ConsultationInfo.Builder();
  }

  /**
   * Creates a new ConsultationInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ConsultationInfo RecordBuilder
   */
  public static com.bytatech.ayoos.appointment.avro.ConsultationInfo.Builder newBuilder(com.bytatech.ayoos.appointment.avro.ConsultationInfo.Builder other) {
    return new com.bytatech.ayoos.appointment.avro.ConsultationInfo.Builder(other);
  }

  /**
   * Creates a new ConsultationInfo RecordBuilder by copying an existing ConsultationInfo instance.
   * @param other The existing instance to copy.
   * @return A new ConsultationInfo RecordBuilder
   */
  public static com.bytatech.ayoos.appointment.avro.ConsultationInfo.Builder newBuilder(com.bytatech.ayoos.appointment.avro.ConsultationInfo other) {
    return new com.bytatech.ayoos.appointment.avro.ConsultationInfo.Builder(other);
  }

  /**
   * RecordBuilder for ConsultationInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ConsultationInfo>
    implements org.apache.avro.data.RecordBuilder<ConsultationInfo> {

    private float height;
    private float weight;
    private int age;
    private java.util.List<com.bytatech.ayoos.appointment.avro.Symptom> symptoms;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.bytatech.ayoos.appointment.avro.ConsultationInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.height)) {
        this.height = data().deepCopy(fields()[0].schema(), other.height);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.weight)) {
        this.weight = data().deepCopy(fields()[1].schema(), other.weight);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.age)) {
        this.age = data().deepCopy(fields()[2].schema(), other.age);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.symptoms)) {
        this.symptoms = data().deepCopy(fields()[3].schema(), other.symptoms);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ConsultationInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.bytatech.ayoos.appointment.avro.ConsultationInfo other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.height)) {
        this.height = data().deepCopy(fields()[0].schema(), other.height);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.weight)) {
        this.weight = data().deepCopy(fields()[1].schema(), other.weight);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.age)) {
        this.age = data().deepCopy(fields()[2].schema(), other.age);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.symptoms)) {
        this.symptoms = data().deepCopy(fields()[3].schema(), other.symptoms);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'height' field.
      * @return The value.
      */
    public java.lang.Float getHeight() {
      return height;
    }

    /**
      * Sets the value of the 'height' field.
      * @param value The value of 'height'.
      * @return This builder.
      */
    public com.bytatech.ayoos.appointment.avro.ConsultationInfo.Builder setHeight(float value) {
      validate(fields()[0], value);
      this.height = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'height' field has been set.
      * @return True if the 'height' field has been set, false otherwise.
      */
    public boolean hasHeight() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'height' field.
      * @return This builder.
      */
    public com.bytatech.ayoos.appointment.avro.ConsultationInfo.Builder clearHeight() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'weight' field.
      * @return The value.
      */
    public java.lang.Float getWeight() {
      return weight;
    }

    /**
      * Sets the value of the 'weight' field.
      * @param value The value of 'weight'.
      * @return This builder.
      */
    public com.bytatech.ayoos.appointment.avro.ConsultationInfo.Builder setWeight(float value) {
      validate(fields()[1], value);
      this.weight = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'weight' field has been set.
      * @return True if the 'weight' field has been set, false otherwise.
      */
    public boolean hasWeight() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'weight' field.
      * @return This builder.
      */
    public com.bytatech.ayoos.appointment.avro.ConsultationInfo.Builder clearWeight() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'age' field.
      * @return The value.
      */
    public java.lang.Integer getAge() {
      return age;
    }

    /**
      * Sets the value of the 'age' field.
      * @param value The value of 'age'.
      * @return This builder.
      */
    public com.bytatech.ayoos.appointment.avro.ConsultationInfo.Builder setAge(int value) {
      validate(fields()[2], value);
      this.age = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'age' field has been set.
      * @return True if the 'age' field has been set, false otherwise.
      */
    public boolean hasAge() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'age' field.
      * @return This builder.
      */
    public com.bytatech.ayoos.appointment.avro.ConsultationInfo.Builder clearAge() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'symptoms' field.
      * @return The value.
      */
    public java.util.List<com.bytatech.ayoos.appointment.avro.Symptom> getSymptoms() {
      return symptoms;
    }

    /**
      * Sets the value of the 'symptoms' field.
      * @param value The value of 'symptoms'.
      * @return This builder.
      */
    public com.bytatech.ayoos.appointment.avro.ConsultationInfo.Builder setSymptoms(java.util.List<com.bytatech.ayoos.appointment.avro.Symptom> value) {
      validate(fields()[3], value);
      this.symptoms = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'symptoms' field has been set.
      * @return True if the 'symptoms' field has been set, false otherwise.
      */
    public boolean hasSymptoms() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'symptoms' field.
      * @return This builder.
      */
    public com.bytatech.ayoos.appointment.avro.ConsultationInfo.Builder clearSymptoms() {
      symptoms = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ConsultationInfo build() {
      try {
        ConsultationInfo record = new ConsultationInfo();
        record.height = fieldSetFlags()[0] ? this.height : (java.lang.Float) defaultValue(fields()[0]);
        record.weight = fieldSetFlags()[1] ? this.weight : (java.lang.Float) defaultValue(fields()[1]);
        record.age = fieldSetFlags()[2] ? this.age : (java.lang.Integer) defaultValue(fields()[2]);
        record.symptoms = fieldSetFlags()[3] ? this.symptoms : (java.util.List<com.bytatech.ayoos.appointment.avro.Symptom>) defaultValue(fields()[3]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ConsultationInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<ConsultationInfo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ConsultationInfo>
    READER$ = (org.apache.avro.io.DatumReader<ConsultationInfo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
